rpi_1089_eac9e86a4d6c26cd703e3df02bbe1bdb604d8a05
commit eac9e86a4d6c26cd703e3df02bbe1bdb604d8a05
Author: Pantelis Antoniou <pantelis.antoniou@konsulko.com>
Date:   Wed Dec 3 13:23:28 2014 +0200

    OF: DT-Overlay configfs interface
    
    This is a port of Pantelis Antoniou's v3 port that makes use of the
    new upstreamed configfs support for binary attributes.
    
    Original commit message:
    
    Add a runtime interface to using configfs for generic device tree overlay
    usage. With it its possible to use device tree overlays without having
    to use a per-platform overlay manager.
    
    Please see Documentation/devicetree/configfs-overlays.txt for more info.
    
    Changes since v2:
    - Removed ifdef CONFIG_OF_OVERLAY (since for now it's required)
    - Created a documentation entry
    - Slight rewording in Kconfig
    
    Changes since v1:
    - of_resolve() -> of_resolve_phandles().
    
    Originally-signed-off-by: Pantelis Antoniou <pantelis.antoniou@konsulko.com>
    Signed-off-by: Phil Elwell <phil@raspberrypi.org>
    
    DT configfs: Fix build errors on other platforms
    
    Signed-off-by: Phil Elwell <phil@raspberrypi.org>
    
    DT configfs: fix build error
    
    There is an error when compiling rpi-4.6.y branch:
      CC      drivers/of/configfs.o
    drivers/of/configfs.c:291:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
       .default_groups = of_cfs_def_groups,
                         ^
    drivers/of/configfs.c:291:21: note: (near initialization for 'of_cfs_subsys.su_group.default_groups.next')
    
    The .default_groups is linked list since commit
    1ae1602de028acaa42a0f6ff18d19756f8e825c6.
    This commit uses configfs_add_default_group to fix this problem.
    
    Signed-off-by: Slawomir Stepien <sst@poczta.fm>


Gbp-Pq: Topic rpi
Gbp-Pq: Name rpi_1089_eac9e86a4d6c26cd703e3df02bbe1bdb604d8a05.patch