rpi_1949_bdb84970a3a7a831ed776e96105671df23e64cfe
commit bdb84970a3a7a831ed776e96105671df23e64cfe
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Thu Feb 9 14:39:42 2017 -0300

    perf bench numa: Avoid possible truncation when using snprintf()
    
    commit 3aff8ba0a4c9c9191bb788171a1c54778e1246a2 upstream.
    
    Addressing this warning from gcc 7:
    
        CC       /tmp/build/perf/bench/numa.o
      bench/numa.c: In function '__bench_numa':
      bench/numa.c:1582:42: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size between 8 and 17 [-Werror=format-truncation=]
           snprintf(tname, 32, "process%d:thread%d", p, t);
                                                ^~
      bench/numa.c:1582:25: note: directive argument in the range [0, 2147483647]
           snprintf(tname, 32, "process%d:thread%d", p, t);
                               ^~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/stdio.h:939:0,
                       from bench/../util/util.h:47,
                       from bench/../builtin.h:4,
                       from bench/numa.c:11:
      /usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 17 and 35 bytes into a destination of size 32
         return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              __bos (__s), __fmt, __va_arg_pack ());
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors
    
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: David Ahern <dsahern@gmail.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Petr Holasek <pholasek@redhat.com>
    Cc: Wang Nan <wangnan0@huawei.com>
    Link: http://lkml.kernel.org/n/tip-twa37vsfqcie5gwpqwnjuuz9@git.kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>


Gbp-Pq: Topic rpi
Gbp-Pq: Name rpi_1949_bdb84970a3a7a831ed776e96105671df23e64cfe.patch