rpi_1416_3343693c634e98bc0f25fec5c0d05ceba984192c
commit 3343693c634e98bc0f25fec5c0d05ceba984192c
Author: Phil Elwell <pelwell@users.noreply.github.com>
Date:   Mon Nov 13 13:00:14 2017 +0000

    USB_DWCOTG: Disable building dwc_otg as a module (#2265)
    
    When dwc_otg is built as a module, build will fail with the following
    error:
    
    ERROR: "DWC_TASK_HI_SCHEDULE" [drivers/usb/host/dwc_otg/dwc_otg.ko] undefined!
    scripts/Makefile.modpost:91: recipe for target '__modpost' failed
    make[1]: *** [__modpost] Error 1
    Makefile:1199: recipe for target 'modules' failed
    make: *** [modules] Error 2
    
    Even if the error is solved by including the missing
    DWC_TASK_HI_SCHEDULE function, the kernel will panic when loading
    dwc_otg.
    
    As a workaround, simply prevent user from building dwc_otg as a module
    as the current kernel does not support it.
    
    See: https://github.com/raspberrypi/linux/issues/2258
    
    Signed-off-by: Malik Olivier Boussejra <malik@boussejra.com>


Gbp-Pq: Topic rpi
Gbp-Pq: Name rpi_1416_3343693c634e98bc0f25fec5c0d05ceba984192c.patch