rpi_1580_01f65aad08112d7e41df01a65cc60da2d86e1c77
commit 01f65aad08112d7e41df01a65cc60da2d86e1c77
Author: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
Date:   Tue Jan 24 15:18:21 2017 -0800

    frv: add atomic64_add_unless()
    
    
    [ Upstream commit 545d58f677b21401f6de1ac12c25cc109f903ace ]
    
    The build of frv allmodconfig was failing with the error:
    lib/atomic64_test.c:209:9: error:
    
    	implicit declaration of function 'atomic64_add_unless'
    
    All the atomic64 operations were defined in frv, but
    atomic64_add_unless() was not done.
    
    Implement atomic64_add_unless() as done in other arches.
    
    Link: http://lkml.kernel.org/r/1484781236-6698-1-git-send-email-sudipm.mukherjee@gmail.com
    Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>
    Cc: David Howells <dhowells@redhat.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
    Signed-off-by: Sasha Levin <alexander.levin@verizon.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>


Gbp-Pq: Topic rpi
Gbp-Pq: Name rpi_1580_01f65aad08112d7e41df01a65cc60da2d86e1c77.patch